# -*- coding: utf-8 -*-
"""Python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJ9dS3GWr0qw7qTgtuarXSNgKFVEwNRu
"""

print("Hello World")

print('Hello World')

print(1+2)

print(2*3)

print(True)

print(False)

a = 3; b = 4; c = a + b; print(c); print(a); print(b)

a = "안녕하세요."
b = "반갑습니다."
c = a + b
print(c)

a = "안녕하세요."
b = a * 10;
print(b)

print("###############")
print("#" * 15)

"""아버지와 어머니 그리고 삼촌에게 감사한 마음을 전하고 싶습니다.
아버지에게는 10만원, 어머니에게는 15만원, 삼촌에게는 "감사합니다."
변수 : _Father, _Mother, _Uncle
"""

_Father = "100,000"
_Mother = "150,000"
_Uncle = "감사합니다."
Thanks = _Father, _Mother, _Uncle
print(Thanks)

_Father = "100,000"
_Mother = "150,000"
_Uncle = "감사합니다."
Thanks = _Father, _Mother, _Uncle
print("아버지 =", _Father, "원")
print("어머니 =", _Mother, "원")
print("삼촌 =", _Uncle)

"""변수의 규칙 : 문자 또는 _로 시작(Father, father, _father), 문자, 숫자, _구성(Father69, father55, father_56), 공백 절대 안된다.안쓰는 것이 좋다. 특수문자 절대 안된다.

FATHER, father, MOTHER, mother, _Father, _father 다 다른 변수이다.
Keyword (True, False, for, while, If, break, class, ...)

숫자자료형 = 숫자 ,문자자료형 = 모든 문자들...
"""

a = 2
b = "2"
c = a + b

"""형변환 : int()-정수형을 변환할때, float()-실수형으로 변환하고자할때, str()-문자자료형으로 변환하고자할때"""

a = 2
b = "2"
c = a + int(b)

"""산술연산자 : + 더하기, - 빼기, * 곱하기, / 나누기, % 나머지, // 몫, ** 거듭제곱

산술연산자 : + 더하기(print(4+3)), - 빼기(print(2-1)), * 곱하기(print(5*4)), / 나누기(print(4/2)), % 나머지(print(5 % 2)), // 몫(print(6 // 2)), ** 거듭제곱(print(4**2))
"""